/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pventa;

import javax.swing.JOptionPane;

/**
 *
 * @author jahziel
 */
public class Cobrar extends javax.swing.JDialog {

    /**
     * Creates new form Cobrar
     */
    dbCon con = new dbCon();
    misFunciones miFun = new misFunciones();
    
    public Cobrar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        txtCobro.setText(varGlobales.sTotalVenta);
        combofPago.setSelectedIndex(0);
        txtRecibido.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        lFormaPago = new javax.swing.JLabel();
        combofPago = new javax.swing.JComboBox<>();
        lCobro = new javax.swing.JLabel();
        txtCobro = new javax.swing.JLabel();
        lRecibido = new javax.swing.JLabel();
        txtRecibido = new javax.swing.JTextField();
        lCambio = new javax.swing.JLabel();
        txtCambio = new javax.swing.JLabel();
        lRef = new javax.swing.JLabel();
        txtRef = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        bAceptar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        bAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check.png"))); // NOI18N
        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bCancelar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel-50.png"))); // NOI18N
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        lFormaPago.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lFormaPago.setText("Forma de pago:");

        combofPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));
        combofPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combofPagoActionPerformed(evt);
            }
        });

        lCobro.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lCobro.setText("Cantidad a cobrar:");

        txtCobro.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        txtCobro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtCobro.setText("0");
        txtCobro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lRecibido.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lRecibido.setText("Cantidad recibida:");

        txtRecibido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRecibidoKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRecibidoKeyReleased(evt);
            }
        });

        lCambio.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lCambio.setText("Cambio:");

        txtCambio.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        txtCambio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtCambio.setText("0.00");
        txtCambio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lRef.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lRef.setText("Referencia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCobro)
                            .addComponent(lRecibido)
                            .addComponent(lCambio)
                            .addComponent(lRef)
                            .addComponent(lFormaPago))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combofPago, 0, 220, Short.MAX_VALUE)
                            .addComponent(txtRecibido)
                            .addComponent(txtCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRef)
                            .addComponent(txtCobro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combofPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFormaPago))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCobro)
                    .addComponent(txtCobro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRecibido)
                    .addComponent(txtRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCambio)
                    .addComponent(txtCambio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRef)
                    .addComponent(txtRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
        varGlobales.bVentaRealizada=false;
        
        // Cierra la Forma
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void combofPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combofPagoActionPerformed
        // TODO add your handling code here:
        if (combofPago.getSelectedItem().equals("Efectivo"))
        {
            // Coloca en blanco la referencia y deshabilita
            txtRef.setText(null);
            txtRef.setEnabled(false);
            txtRecibido.setEnabled(true);
        }
        else
        {
            // Coloca la cantidad a cobrar exacta
            txtRecibido.setText(txtCobro.getText());            
            txtRef.setEnabled(true);
            txtCambio.setText("0.00");
            txtRecibido.setEnabled(false);
            
        }
    }//GEN-LAST:event_combofPagoActionPerformed

    private void txtRecibidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRecibidoKeyReleased
        // TODO add your handling code here:
        sbCalculaCambio();
    }//GEN-LAST:event_txtRecibidoKeyReleased

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        // TODO add your handling code here:
        if (fnBoolCobroCorrecto())
        {
            // Acepta la Venta
            varGlobales.bVentaRealizada=true;
            
            // Forma de Pago
            varGlobales.sFormaPago = combofPago.getSelectedItem().toString();
            varGlobales.sReferencia = txtRef.getText().toString();
            
             // Cierra la Forma
             this.dispose();
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void txtRecibidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRecibidoKeyTyped
        // TODO add your handling code here:
        if ((int)evt.getKeyChar()<48 || (int)evt.getKeyChar()>57)
            if ((int)evt.getKeyChar()==46)
            {
                if (txtRecibido.getText().lastIndexOf(".")>=0)
                    evt.consume();
                    
            }
            else
                evt.consume();
    }//GEN-LAST:event_txtRecibidoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cobrar dialog = new Cobrar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
 private void sbCalculaCambio()
    {
        double douPagar;
        double douRecibida;
        double  douCambio;
        
        if (! txtCobro.getText().isEmpty() && ! txtRecibido.getText().isEmpty())
        {

            if(miFun.strDec(txtRecibido.getText())){
            douPagar = Float.valueOf(txtCobro.getText());

            // Obtengo la Cantidad Recibida
            douRecibida = Float.valueOf(txtRecibido.getText());

            // Calculo la diferencia hasta que sea mayor o igual la cantidad recibida
            if (douRecibida >= douPagar)
            {
                // Calculo el Cambio
                douCambio = douRecibida-douPagar;

                // Coloca el cambio
                if (douCambio>9)
                   txtCambio.setText(String.format("%5.2f",douCambio));            
                else
                   txtCambio.setText(String.format("%1.2f",douCambio));             
                
            }
            else
                // Coloca el cambio en 0
                txtCambio.setText("0.00");            
                
            }
            // Obtengo la Cantidad a Pagar
                
        
        }else{
            txtCambio.setText("0.00");
        }
    }
 
 private boolean fnBoolCobroCorrecto()
    {
        // Variable para el resultado
        boolean bResult = true;
        
        // Si es efectivo
        if(txtCobro.getText().equals(txtRecibido.getText())){
            bResult = true;
        }
        else if (combofPago.getSelectedIndex()==0)
        {
            if (txtCambio.getText().equals("0.00"))
            {
                
                //oFunc.SubSistemaMensaje("Error en Cantidad Recibida");
                JOptionPane.showMessageDialog(null, "Error en la cantidad","Duran Gourmet",JOptionPane.INFORMATION_MESSAGE);                
                txtRecibido.requestFocus();
                bResult=false;
            }
        }
        else
            // Si esta tarjeta de credito
            if (txtRef.getText().trim().isEmpty())
            {
                //oFunc.SubSistemaMensaje("Capture Referencia");
                JOptionPane.showMessageDialog(null, "Se necesita una Referencia","Duran Gourmet",JOptionPane.INFORMATION_MESSAGE);                
                txtRef.requestFocus();
                bResult=false;
            }
        return bResult;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JComboBox<String> combofPago;
    private javax.swing.JLabel lCambio;
    private javax.swing.JLabel lCobro;
    private javax.swing.JLabel lFormaPago;
    private javax.swing.JLabel lRecibido;
    private javax.swing.JLabel lRef;
    private javax.swing.JLabel txtCambio;
    private javax.swing.JLabel txtCobro;
    private javax.swing.JTextField txtRecibido;
    private javax.swing.JTextField txtRef;
    // End of variables declaration//GEN-END:variables
}
